### ISSUE TITLE
Bug in the file "resellerclubvpsus.php"

### ISSUE THREAD

**Issue by rafaeloliveiraz** [directi/whmcs-resellerclub-modules#22] opened 2016-02-02 11:30 UTC
When I click the folder "resellerclubvpsus" in WHMCS can not add any new product or server and it is not possible to carry out editing of both.

The error range is as follows:

"Fatal error: Cannot redeclare _createCustomer() (previously declared in /home/nefuxcom/public_html/painel/modules/servers/resellerclubmdhostingin/resellerclubmdhostingin.php:483) in /home/nefuxcom/public_html/painel/modules/servers/resellerclubvpsus/resellerclubvpsus.php on line 486"

The version of My WHMCS is V6.2.1.
I'm still trying to fix it but if anyone has any idea thank.

**Comment by rafaeloliveiraz** [comment] 2016-02-02 11:33
The most interesting is that I contacted the ResellerClub to report the error and request some help to fix and they were very direct in saying that it should be treated with WHMCS, they are developers, and when I contacted the WHMCS they were also direct and reported that it is the responsibility of ResellerClub because the module is theirs ... lol

**Comment by viral-patel** [comment] 2016-08-30 09:21
@rafaeloliveiraz : confirm if your the issue is fixed in latest commit.

**Closed by viral-patel** 2016-08-30 09:21 UTC
Labels: bug

**Comment by neilomar** [comment] 2019-02-20 20:49
este erro voltou a acontecer... desta vez, não e somente com o resellerclubvpsus, e sim com a maioria dos outros produtos do modulo

**Comment by neilomar** [comment] 2019-02-20 20:50
this error happened again ... this time, not only with resellerclubvpsus, but with most other products of the module
